name: Run tests

on: [push, pull_request]
# if we want to limit builds on changes to code only
  # pull_request:
    # paths:
    #   - "**/*.go"
  # push:
    # paths:
    #   - "**/*.go"
    #   - "**/*.yaml"

jobs:
  test-linux:
    strategy:
      matrix:
        # we can add multiple versions of go here. each one will generate a different (parallel) build
        go: ['1.13.4']
        # we can also add multiple oses here. in conjunction with other parameters (go version for example) it will generate
        # multiple parallel builds
        os: [ubuntu-16.04] # ubuntu-16.04 and ubuntu-18.04 available out of the box
    name: Run integration tests in ${{matrix.os}} with go ${{matrix.go}}
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}
      - name: run integration tests
        run: |
          make build-ci
  # we could have included windows above, but we can't becuase we're using "make"
  test-windows:
    strategy:
      matrix:
        go: ['1.13.4']
        os: [windows-2019] # only 2019 one avaialable out of the box
    name: Run integration tests in ${{matrix.os}} with go ${{matrix.go}}
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}
      - name: run integration tests
      # we don't have 'make' on windows. 
      # if we want to mimic linux tests we'll have to create a powershell/batch script for windows
        run: |
          go test --tags=integration ./...
